name: Feature Request
description: Propose a new feature, analyzer capability, or enhancement
title: "feat: [Short summary of the feature]"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement to Insight CLI!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem or limitation?
      placeholder: I am frustrated when trying to analyze a codebase containing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution / Feature
      description: A clear and concise description of what you want to happen.
      placeholder: Add support for analyzing Go files or support exporting reports to HTML...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you have considered.
      placeholder: Running cloc or manually summarizing files...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any mockups, CLI design ideas, or reference implementations.
